import Head from "next/head";
import fetcher from "constants/fetcher";

export default function Home({ data }) {
  console.log(data);

  return (
    <>
      <Head>
        <title>Next Flix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="">
        <h1>Home</h1>
      </div>
    </>
  );
}

export async function getStaticProps(context) {
  const response = await fetcher("discover/movie");
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}
