import Head from "next/head";
import fetcher from "constants/fetcher";
import Link from "next/link";
import slugify from "constants/slugify";

export default function Home({ data }) {
  console.log(data);

  return (
    <>
      <Head>
        <title>Next Flix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="">
        <h1>Home</h1>
        <ul>
          {data.results.map((filme) => (
            <li key={filme.id}>
              <Link href={`filmes/${slugify(filme.title)}?id=${filme.id}`}>
                {filme.title}
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}

export async function getServerSideProps(context) {
  const response = await fetcher("discover/movie");
  const data = await response.json();
  return {
    props: { data },
  };
}
